# Generated by Django 5.1 on 2025-02-18 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(choices=[('engineer', 'Engineer'), ('farmer', 'Farmer'), ('professor', 'Professor'), ('economist', 'Economist'), ('sportman', 'Sportman'), ('artist', 'Artist')], default='artist', max_length=255)),
                ('salary', models.FloatField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Hot')], default='male', max_length=255)),
                ('country', models.CharField(choices=[('albania', 'Albania'), ('andorra', 'Andorra'), ('armenia', 'Armenia'), ('austria', 'Austria'), ('azerbaijan', 'Azerbaijan'), ('belarus', 'Belarus'), ('belgium', 'Belgium'), ('bosnia_and_herzegovina', 'Bosnia and Herzegovina'), ('bulgaria', 'Bulgaria'), ('croatia', 'Croatia'), ('cyprus', 'Cyprus'), ('czech_republic', 'Czech Republic'), ('denmark', 'Denmark'), ('estonia', 'Estonia'), ('finland', 'Finland'), ('france', 'France'), ('georgia', 'Georgia'), ('germany', 'Germany'), ('greece', 'Greece'), ('hungary', 'Hungary'), ('iceland', 'Iceland'), ('ireland', 'Ireland'), ('italy', 'Italy'), ('kazakhstan', 'Kazakhstan'), ('kosovo', 'Kosovo'), ('latvia', 'Latvia'), ('liechtenstein', 'Liechtenstein'), ('lithuania', 'Lithuania'), ('luxembourg', 'Luxembourg'), ('malta', 'Malta'), ('moldova', 'Moldova'), ('monaco', 'Monaco'), ('montenegro', 'Montenegro'), ('netherlands', 'Netherlands'), ('north_macedonia', 'North Macedonia'), ('norway', 'Norway'), ('poland', 'Poland'), ('portugal', 'Portugal'), ('romania', 'Romania'), ('russia', 'Russia'), ('san_marino', 'San Marino'), ('serbia', 'Serbia'), ('slovakia', 'Slovakia'), ('slovenia', 'Slovenia'), ('spain', 'Spain'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('turkey', 'Turkey'), ('ukraine', 'Ukraine'), ('united_kingdom', 'United Kingdom'), ('vatican_city', 'Vatican City')], default='austria', max_length=255)),
                ('weather', models.CharField(choices=[('cold', 'Cold'), ('hot', 'Hot'), ('mild', 'Mild')], default='cold', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
