# Generated by Django 5.1 on 2025-02-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='country',
        ),
        migrations.RemoveField(
            model_name='form',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='form',
            name='work',
        ),
        migrations.AddField(
            model_name='form',
            name='agriculture_economy',
            field=models.CharField(choices=[('Sí, prefiero un país con oportunidades en agricultura.', 'Si'), ('No, prefiero un país con una economía diversificada.', 'No'), ('No me importa.', 'No Importa')], default='Sí, prefiero un país con oportunidades en agricultura.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='air_pollution',
            field=models.CharField(choices=[('Muy importante, quiero vivir en un país con baja contaminación.', 'Muy Importante'), ('No me importa mucho.', 'No Importa')], default='Muy importante, quiero vivir en un país con baja contaminación.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='company_registration',
            field=models.CharField(choices=[('Sí, quiero facilidades para emprender.', 'Si'), ('No me importa.', 'No')], default='Sí, quiero facilidades para emprender.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='ease_of_business',
            field=models.CharField(choices=[('Muy importante (Quiero emprender o invertir).', 'Muy Importante'), ('Moderadamente importante (Podría considerar oportunidades).', 'Moderado'), ('No es importante para mí.', 'No Importante')], default='Muy importante (Quiero emprender o invertir).', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='electricity_access',
            field=models.CharField(choices=[('Muy importante.', 'Muy Importante'), ('No me importa.', 'No Importa')], default='Muy importante.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='export_economy',
            field=models.CharField(choices=[('Sí, quiero un país con un alto nivel de comercio internacional.', 'Si'), ('No es relevante para mí.', 'No Importa')], default='Sí, quiero un país con un alto nivel de comercio internacional.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='foreign_investment',
            field=models.CharField(choices=[('Muy importante.', 'Muy Importante'), ('No me importa.', 'No Importa')], default='Muy importante.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='healthcare_importance',
            field=models.CharField(choices=[('Muy importante, quiero un país con buena atención médica.', 'Muy Importante'), ('No me importa mucho.', 'No Importa')], default='Muy importante, quiero un país con buena atención médica.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='job_security',
            field=models.CharField(choices=[('Prefiero un país con empleos estables y buenos contratos.', 'Empleos Estables'), ('No me importa si el empleo es informal o vulnerable.', 'Informal')], default='Prefiero un país con empleos estables y buenos contratos.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='living_area',
            field=models.CharField(choices=[('Ciudad', 'Ciudad'), ('Rural', 'Rural'), ('No me importa', 'No Importa')], default='Ciudad', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='low_taxes',
            field=models.CharField(choices=[('Sí, quiero un país con menor carga impositiva.', 'Si'), ('No me importa.', 'No')], default='Sí, quiero un país con menor carga impositiva.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='mobile_access',
            field=models.CharField(choices=[('Muy importante.', 'Muy Importante'), ('No me importa.', 'No Importa')], default='Muy importante.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='poverty_reduction',
            field=models.CharField(choices=[('Muy importante, quiero un país con menos desigualdad.', 'Muy Importante'), ('No es una prioridad.', 'No Importa')], default='Muy importante, quiero un país con menos desigualdad.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='research_development',
            field=models.CharField(choices=[('Sí, prefiero un país innovador.', 'Si'), ('No es una prioridad para mí.', 'No')], default='Sí, prefiero un país innovador.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='unemployment_rate',
            field=models.CharField(choices=[('Quiero un país con muy baja tasa de desempleo.', 'Baja Tasa'), ('No me importa mucho la tasa de desempleo.', 'No Importa')], default='Quiero un país con muy baja tasa de desempleo.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='unemployment_support',
            field=models.CharField(choices=[('Sí, quiero un país con apoyo social.', 'Si'), ('No me importa.', 'No')], default='Sí, quiero un país con apoyo social.', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='work_sector',
            field=models.CharField(choices=[('Agricultura / Pesca', 'Agricultura Pesca'), ('Tecnología / Innovación', 'Tecnologia Innovacion'), ('Negocios / Emprendimiento', 'Negocios Emprendimiento'), ('Educación / Salud', 'Educacion Salud'), ('Industria / Manufactura', 'Industria Manufactura'), ('Otros', 'Otros')], default='Tecnología / Innovación', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('Hombre', 'Male'), ('Mujer', 'Female')], default='Hombre', max_length=255),
        ),
    ]
