# Generated by Django 5.1 on 2025-02-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_form_country_remove_form_weather_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='mobile_access',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='form',
            name='foreign_investment',
            field=models.CharField(choices=[('Muy importante.', 'Muy Importante'), ('No me importa.', 'No Importa')], default='No me importa.', max_length=255),
        ),
    ]
