# Generated by Django 5.1 on 2025-02-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_mobile_access_form_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='mobile',
            new_name='mobile_access',
        ),
        migrations.AlterField(
            model_name='form',
            name='foreign_investment',
            field=models.CharField(choices=[('Muy importante.', 'Muy Importante'), ('No me importa.', 'No Importa')], default='Muy importante.', max_length=255),
        ),
    ]
