# Generated by Django 5.1 on 2025-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_form_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='agriculture_economy',
        ),
        migrations.RemoveField(
            model_name='form',
            name='company_registration',
        ),
        migrations.RemoveField(
            model_name='form',
            name='ease_of_business',
        ),
        migrations.RemoveField(
            model_name='form',
            name='electricity_access',
        ),
        migrations.RemoveField(
            model_name='form',
            name='export_economy',
        ),
        migrations.RemoveField(
            model_name='form',
            name='low_taxes',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mobile_access',
        ),
        migrations.RemoveField(
            model_name='form',
            name='poverty_reduction',
        ),
        migrations.RemoveField(
            model_name='form',
            name='research_development',
        ),
        migrations.RemoveField(
            model_name='form',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='form',
            name='unemployment_support',
        ),
        migrations.RemoveField(
            model_name='form',
            name='work_sector',
        ),
        migrations.AddField(
            model_name='form',
            name='city_growth',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='corruption',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='country_salary',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='economy',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='freedom',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='low_inflation',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='air_pollution',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='foreign_investment',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='healthcare_importance',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='job_security',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='living_area',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='unemployment_rate',
            field=models.CharField(choices=[('Muy importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco importante', 'Poco Importante'), ('Nada importante', 'Nada Importante')], default='Importante', max_length=255),
        ),
    ]
